#!/usr/bin/env python3
"""Weather condition sprites for the RetroNews CITY FORECAST tile.

    python scripts/gen_wx_icons.py dashboard/retronews_wx.png

A 2-frame sprite per condition, 14x14 logical each, laid out as
2 columns (frames) x N rows (conditions) = 28 x 14N.

WHY 2 FRAMES AND NOT MORE
This is a GBA weather icon, not a particle system. Handheld sprites animated on
two or three cels held for several frames each, and at 24fps a two-cel swap held
~250ms is unmistakable motion for one property write. Everything here moves by
SWAPPING A CEL — nothing interpolates, nothing tweens, and the compositor sees a
background-position change.

WHY HAND-AUTHORED STRING ART
PIL's ellipse and line at 14x14 produce mush: anti-aliased edges that quantize
into lopsided blobs, and a sun that reads as a smudge. At this size every pixel
is a decision, so the icons are drawn as character grids and the palette is
looked up per character. Same reason the host sheet is art rather than geometry.

PALETTE IS THE SCREEN TIER (--scr*/--gold/--cyan), because these live INSIDE a
tile. Nothing here may use shell colours.
"""
from __future__ import annotations

import sys
from PIL import Image

CELL = 14

# Screen-tier palette, mirrored from retronews.css :root.
PAL = {
    '.': (0, 0, 0, 0),              # transparent
    'O': (0x06, 0x0a, 0x20, 255),   # --scr-shade, outline
    'S': (0xff, 0xc8, 0x30, 255),   # --gold, sun body
    'H': (0xff, 0xe8, 0x9a, 255),   # sun highlight
    'C': (0xf4, 0xf8, 0xff, 255),   # --scr-ink, cloud
    'D': (0x8f, 0xa4, 0xd8, 255),   # --scr-dim, cloud shade
    'R': (0x46, 0xdc, 0xff, 255),   # --cyan, rain / snow
    'B': (0xff, 0xc8, 0x30, 255),   # bolt
}

# ── the sprites ──────────────────────────────────────────────────────────────
# Frame A and frame B per condition. The DIFFERENCE between them is the whole
# animation, so it is kept to one legible idea each: rays pulse, drops fall a
# row, the bolt strikes. Nothing drifts sideways — lateral motion at 14px reads
# as juddering rather than as weather.
SUN_A = """
......OO......
......OO......
..O........O..
...O......O...
....OSSSSO....
....SHHHHS....
OO..SHHHHS..OO
OO..SHHHHS..OO
....SHHHHS....
....OSSSSO....
...O......O...
..O........O..
......OO......
......OO......
"""
SUN_B = """
..............
......OO......
...O......O...
..............
....OSSSSO....
....SHHHHS....
.O..SHHHHS..O.
.O..SHHHHS..O.
....SHHHHS....
....OSSSSO....
..............
...O......O...
......OO......
..............
"""
# Sun behind cloud: the sun cel changes, the cloud never does. A cloud that
# jitters reads as a glitch; a sun that pulses behind it reads as weather.
PCLOUD_A = """
.........OO...
..O......OO...
...O..........
....OSSSSO....
....SHHHHS..OO
.OO.SHHHHS..OO
...OOSSSSO....
..OCCCCCCCO...
.OCCCCCCCCCO..
OCCCCCCCCCCCO.
OCCCCCCCCCCCO.
.ODDDDDDDDDO..
..OOOOOOOOO...
..............
"""
PCLOUD_B = """
..............
.........OO...
..O...........
....OSSSSO....
....SHHHHS....
..O.SHHHHS..O.
...OOSSSSO....
..OCCCCCCCO...
.OCCCCCCCCCO..
OCCCCCCCCCCCO.
OCCCCCCCCCCCO.
.ODDDDDDDDDO..
..OOOOOOOOO...
..............
"""
# Overcast: the only thing that moves is a highlight travelling the top edge,
# which is palette motion in sprite form and costs nothing.
CLOUD_A = """
..............
....OOOOO.....
..OOCCCCCOO...
.OCCCCCCCCCO..
OCCCCCCCCCCCO.
OCCCCCCCCCCCO.
OCCCCCCCCCCCO.
OCDDDDDDDDDCO.
.ODDDDDDDDDO..
..OOOOOOOOO...
..............
..............
..............
..............
"""
CLOUD_B = """
..............
....OOOOO.....
..OOCCCCCOO...
.OCCCCCCCCCO..
OCCCCCCCCCCCO.
OCCCCCCCCCCCO.
OCCCCCCCCCCCO.
OCCCDDDDDDDCO.
.ODDDDDDDDDO..
..OOOOOOOOO...
..............
..............
..............
..............
"""
FOG_A = """
..............
..OOOOOOOOOO..
..DDDDDDDDDD..
..............
.OOOOOOOOOOOO.
.DDDDDDDDDDDD.
..............
..OOOOOOOOOO..
..DDDDDDDDDD..
..............
.OOOOOOOOOOOO.
.DDDDDDDDDDDD.
..............
..............
"""
FOG_B = """
..............
.OOOOOOOOOOOO.
.DDDDDDDDDDDD.
..............
..OOOOOOOOOO..
..DDDDDDDDDD..
..............
.OOOOOOOOOOOO.
.DDDDDDDDDDDD.
..............
..OOOOOOOOOO..
..DDDDDDDDDD..
..............
..............
"""
RAIN_A = """
....OOOOO.....
..OOCCCCCOO...
.OCCCCCCCCCO..
OCCCCCCCCCCCO.
OCDDDDDDDDDCO.
.OOOOOOOOOOO..
..............
..R...R...R...
..R...R...R...
..............
....R...R.....
....R...R.....
..............
..............
"""
RAIN_B = """
....OOOOO.....
..OOCCCCCOO...
.OCCCCCCCCCO..
OCCCCCCCCCCCO.
OCDDDDDDDDDCO.
.OOOOOOOOOOO..
..R...R...R...
..R...R...R...
..............
....R...R.....
....R...R.....
..............
..............
..............
"""
SHOWERS_A = """
....OOOOO.....
..OOCCCCCOO...
.OCCCCCCCCCO..
OCCCCCCCCCCCO.
OCDDDDDDDDDCO.
.OOOOOOOOOOO..
..RR..RR..RR..
..RR..RR..RR..
..............
...RR..RR.....
...RR..RR.....
..............
..............
..............
"""
SHOWERS_B = """
....OOOOO.....
..OOCCCCCOO...
.OCCCCCCCCCO..
OCCCCCCCCCCCO.
OCDDDDDDDDDCO.
.OOOOOOOOOOO..
..............
..RR..RR..RR..
..RR..RR..RR..
..............
...RR..RR.....
...RR..RR.....
..............
..............
"""
SNOW_A = """
....OOOOO.....
..OOCCCCCOO...
.OCCCCCCCCCO..
OCCCCCCCCCCCO.
OCDDDDDDDDDCO.
.OOOOOOOOOOO..
..............
..R...R...R...
.RRR.RRR.RRR..
..R...R...R...
..............
....R...R.....
...RRR.RRR....
....R...R.....
"""
SNOW_B = """
....OOOOO.....
..OOCCCCCOO...
.OCCCCCCCCCO..
OCCCCCCCCCCCO.
OCDDDDDDDDDCO.
.OOOOOOOOOOO..
....R...R.....
...RRR.RRR....
....R...R.....
..............
..R...R...R...
.RRR.RRR.RRR..
..R...R...R...
..............
"""
# The bolt STRIKES rather than moves: frame B is the flash. A single frame of
# full-brightness against a dark cel is the loudest thing a 2-cel sprite can do,
# and it costs exactly one cel.
STORM_A = """
....OOOOO.....
..OOCCCCCOO...
.OCCCCCCCCCO..
OCCCCCCCCCCCO.
OCDDDDDDDDDCO.
.OOOOOOOOOOO..
......OBB.....
.....OBB......
....OBBBBB....
.......BB.....
......BB......
.....BB.......
..............
..............
"""
STORM_B = """
....OOOOO.....
..OOHHHHHOO...
.OHHHHHHHHHO..
OHHHHHHHHHHHO.
OHDDDDDDDDDHO.
.OOOOOOOOOOO..
......BBB.....
.....BBB......
....BBBBBB....
.......BBB....
......BBB.....
.....BBB......
..............
..............
"""

# Row order is the contract with retronews.js — WX_ICON there must match.
ICONS = [
    ('CLEAR',   SUN_A,     SUN_B),
    ('PCLOUDY', PCLOUD_A,  PCLOUD_B),
    ('CLOUDY',  CLOUD_A,   CLOUD_B),
    ('FOG',     FOG_A,     FOG_B),
    ('RAIN',    RAIN_A,    RAIN_B),
    ('SHOWERS', SHOWERS_A, SHOWERS_B),
    ('SNOW',    SNOW_A,    SNOW_B),
    ('STORM',   STORM_A,   STORM_B),
]


def draw(art: str) -> Image.Image:
    rows = [r for r in art.strip('\n').split('\n')]
    if len(rows) != CELL:
        raise SystemExit(f'sprite must be {CELL} rows, got {len(rows)}')
    im = Image.new('RGBA', (CELL, CELL), (0, 0, 0, 0))
    px = im.load()
    for y, row in enumerate(rows):
        if len(row) != CELL:
            raise SystemExit(f'row {y} must be {CELL} chars, got {len(row)}: {row!r}')
        for x, ch in enumerate(row):
            if ch not in PAL:
                raise SystemExit(f'unknown palette char {ch!r} at {x},{y}')
            px[x, y] = PAL[ch]
    return im


def main() -> int:
    dst = sys.argv[1] if len(sys.argv) > 1 else 'dashboard/retronews_wx.png'
    sheet = Image.new('RGBA', (CELL * 2, CELL * len(ICONS)), (0, 0, 0, 0))
    for r, (name, a, b) in enumerate(ICONS):
        sheet.alpha_composite(draw(a), (0, r * CELL))
        sheet.alpha_composite(draw(b), (CELL, r * CELL))
        print(f'  row {r}  {name}')
    sheet.save(dst)

    data = list(sheet.getdata())
    cols = {p[:3] for p in data if p[3]}
    semi = sum(1 for p in data if 0 < p[3] < 255)
    ok = semi == 0 and sheet.size == (CELL * 2, CELL * len(ICONS))
    print(f'sheet {sheet.size[0]}x{sheet.size[1]}  colours={len(cols)}  semi-alpha={semi}')
    print('  ' + ('PASS' if ok else 'FAIL'))
    return 0 if ok else 1


if __name__ == '__main__':
    sys.exit(main())
